name: Angular Build

# {1}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular: # Name of our first job
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2} Gets our source code
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3} Sets up the environment
      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: e-voting-angular-app/package-lock.json

      # {4}
      - name: Install dependencies
        run: npm ci
        working-directory: e-voting-angular-app
      # {5}
      - name: Run tests
        run: npm run test:ci
        working-directory: e-voting-angular-app
      # {6}
      - name: Build
        run: npm run build # Makes sure the application can be built with no issues
        working-directory: e-voting-angular-app
      # Continuous Deployment (CD) - Build and Push a Docker Image to Registry (Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t e-voting-angular-app .

      - name: Push Docker image to Docker Hub
        run: |
          docker push e-voting-angular-app
        
